name: 'Deploy'
inputs:
  deploy-env:  # id of input
    description: 'test/stage/prod'
    required: true
runs:
  using: "composite"
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  steps:
    - name: Env Deploy
      run: echo "Deploying to ${{ inputs.deploy-env }}"
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2 
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh-actions-eks
        aws-region: us-east-2
    - name: Install Dependencies
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh 
        chmod 700 get_helm.sh 
        ./get_helm.sh
        curl -LO https://dl.k8s.io/release/v1.27.5/bin/linux/amd64/kubectl
    - name: Add Image Tag
      id: tag-image
      run: |
        MANIFEST=$(aws ecr batch-get-image --repository-name cicd_tutorial --image-ids imageTag=${{ github.sha }} --output text --query images[].imageManifest)
        echo "$MANIFEST"
        IMAGE_TAG=${{ inputs.deploy-env }}-${GITHUB_SHA::7}-$(date +%s)
        echo "$IMAGE_TAG"
        aws ecr put-image --repository-name cicd_tutorial --image-tag $IMAGE_TAG --image-manifest "$MANIFEST"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
    - name: Deploy with Helm
      run: |
        aws eks --region us-east-2 update-kubeconfig --name education-eks-demo 
        echo ${{ steps.tag-image.outputs.IMAGE_TAG }}
        echo ${{ steps.tag-image.outputs }}
        helm upgrade --install --set image.repository=${{ secrets.ECR_REPOSITORY }} --set image.tag=${{ steps.tag-image.outputs.IMAGE_TAG }} ${{ inputs.deploy-env }}-demo ./demo 
