name: Build and Push Image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build Image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh-actions-ecr
          aws-region: us-east-2
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ secrets.login-ecr.outputs.registry }}
          REPOSITORY: cicd_tutorial 
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
