name: Build and Push Image
on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - run: echo "Build triggered by a ${{ github.event_name }} event." 
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh-actions-ecr
          aws-region: us-east-2
      - name: Check if image exists
        id: check-image-lock
        run: |
          output=$(./.github/scripts/check-image.sh ${{ github.sha }})
          echo $output
          if echo "$output" | grep -q "STATUS:IMAGE_EXISTS"; then
            echo "Image exists"
          elif echo "$output" | grep -q "STATUS:ERROR"; then
            echo "Image timeout or build image error.  Exiting"
            exit 1;
          elif echo "$output" | grep -q "STATUS:IMAGE_LOCK_NOT_FOUND"; then
            echo "No image found, proceed with building"
            echo "BUILD_IMAGE=true" >> $GITHUB_OUTPUT
          else
            echo "Unknown check image script result"
            exit 2;
          fi
          exit 3
      - name: Login to Amazon ECR
        if: ${{ steps.check-image-lock.outputs.BUILD_IMAGE == 'true' }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'
      - name: Build, tag, and push docker image to Amazon ECR
        if: ${{ steps.check-image-lock.outputs.BUILD_IMAGE == 'true' }} 
        env:
          REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "${{ steps.check-image-lock.outputs.BUILD_IMAGE }}"
          docker build -t $REPOSITORY:$IMAGE_TAG .
          docker push $REPOSITORY:$IMAGE_TAG
          ./.github/scripts/mark-image-as-built.sh ${{ github.sha }} ci-image-lock-demo
      - name: Build Failure Step
        if: ${{ failure() }} 
        run: |
          ./.github/scripts/remove-image-lock-file.sh ${{ github.sha }} cicd_tutorial ci-image-lock-demo us-east-2
  deploy-stage:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: ['build-push-image']
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh-actions-eks
          aws-region: us-east-2
      - name: Install Dependencies
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh 
          chmod 700 get_helm.sh 
          ./get_helm.sh
          curl -LO https://dl.k8s.io/release/v1.27.5/bin/linux/amd64/kubectl
      - name: Add Image Tag
        id: tag-image
        run: |
          MANIFEST=$(aws ecr batch-get-image --repository-name cicd_tutorial --image-ids imageTag=${{ github.sha }} --output text --query images[].imageManifest)
          echo "$MANIFEST"
          IMAGE_TAG=stage-${GITHUB_SHA::7}-$(date +%s)
          echo "$IMAGE_TAG"
          aws ecr put-image --repository-name cicd_tutorial --image-tag $IMAGE_TAG --image-manifest "$MANIFEST"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Deploy with Helm
        run: |
          aws eks --region us-east-2 update-kubeconfig --name education-eks-demo 
          echo ${{ steps.tag-image.outputs.IMAGE_TAG }}
          echo ${{ steps.tag-image.outputs }}
          helm upgrade --install --set image.repository=${{ secrets.ECR_REPOSITORY }} --set image.tag=${{ steps.tag-image.outputs.IMAGE_TAG }} stage-demo ./demo 
    
  deploy-test:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    needs: ['build-push-image']
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - run: echo "Build triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh-actions-eks
          aws-region: us-east-2
      - name: Install Dependencies
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh 
          chmod 700 get_helm.sh 
          ./get_helm.sh
          curl -LO https://dl.k8s.io/release/v1.27.5/bin/linux/amd64/kubectl
      - name: Add Image Tag
        id: tag-image
        run: |
          MANIFEST=$(aws ecr batch-get-image --repository-name cicd_tutorial --image-ids imageTag=${{ github.sha }} --output text --query images[].imageManifest)
          echo "$MANIFEST"
          IMAGE_TAG=test-${GITHUB_SHA::7}-$(date +%s)
          echo "$IMAGE_TAG"
          aws ecr put-image --repository-name cicd_tutorial --image-tag $IMAGE_TAG --image-manifest "$MANIFEST"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Deploy with Helm
        run: |
          aws eks --region us-east-2 update-kubeconfig --name education-eks-demo 
          echo ${{ steps.tag-image.outputs.IMAGE_TAG }}
          echo ${{ steps.tag-image.outputs }}
          helm upgrade --install --set image.repository=${{ secrets.ECR_REPOSITORY }} --set image.tag=${{ steps.tag-image.outputs.IMAGE_TAG }} test-demo ./demo 

  deploy-prod:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    needs: ['build-push-image']
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - run: echo "Build triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/gh-actions-eks
          aws-region: us-east-2
      - name: Install Dependencies
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh 
          chmod 700 get_helm.sh 
          ./get_helm.sh
          curl -LO https://dl.k8s.io/release/v1.27.5/bin/linux/amd64/kubectl
      - name: Add Image Tag
        id: tag-image
        run: |
          MANIFEST=$(aws ecr batch-get-image --repository-name cicd_tutorial --image-ids imageTag=${{ github.sha }} --output text --query images[].imageManifest)
          echo "$MANIFEST"
          IMAGE_TAG=prod-${GITHUB_SHA::7}-$(date +%s)
          echo "$IMAGE_TAG"
          aws ecr put-image --repository-name cicd_tutorial --image-tag $IMAGE_TAG --image-manifest "$MANIFEST"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Deploy with Helm
        run: |
          aws eks --region us-east-2 update-kubeconfig --name education-eks-demo 
          echo ${{ steps.tag-image.outputs.IMAGE_TAG }}
          echo ${{ steps.tag-image.outputs }}
          helm upgrade --install --set image.repository=${{ secrets.ECR_REPOSITORY }} --set image.tag=${{ steps.tag-image.outputs.IMAGE_TAG }} prod-demo ./demo 
